all:
	javac Hello.java -classpath "../.." -encoding UTF-8
	javac Frequencer.java -classpath "../.." -encoding UTF-8
	javac InformationEstimator.java -classpath "../.." -encoding UTF-8
	javac TestCase.java -classpath "../.." -encoding UTF-8
run:
#	java -classpath "../.." s4.B193335/Hello
#	java -classpath "../.." s4.B193335/Frequencer
	java -classpath "../.." s4.B193335/InformationEstimator
#	java -classpath "../.." s4.B193335/TestCase
